# ========================================
# DATA MODELS - Pydantic Models for Validation
# ========================================

from pydantic import BaseModel
from typing import Optional


# Book model - used for responses and full book data
class Book(BaseModel):
    """
    Book model for API responses
    
    Attributes:
        id: Unique identifier for the book (auto-generated)
        title: Title of the book
        author: Author of the book
    """
    id: Optional[int] = None
    title: str
    author: str

    class Config:
        json_schema_extra = {
            "example": {
                "id": 1,
                "title": "The Great Gatsby",
                "author": "F. Scott Fitzgerald"
            }
        }


# BookCreate model - used for POST requests (creating new books)
class BookCreate(BaseModel):
    """
    Model for creating a new book
    
    Note: ID is NOT included here because it's auto-generated by the server
    """
    title: str
    author: str

    class Config:
        json_schema_extra = {
            "example": {
                "title": "The Great Gatsby",
                "author": "F. Scott Fitzgerald"
            }
        }


# BookUpdate model - used for PUT requests (updating books)
class BookUpdate(BaseModel):
    """
    Model for updating a book
    
    Note: Both fields are optional so you can update just one field if needed
    """
    title: Optional[str] = None
    author: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "title": "Updated Title",
                "author": "Updated Author"
            }
        }
